const data = {
  'patients': [
    {
      'patientId': 123,
      'firstName': 'Andrew',
      'lastName': 'Fung',
      'DOB': 6071912,
      'Image': require('./assets/elderlymanavatar1.png'),
      'Age': 24,
      'roomNum': 101,
      'weight': 59,
      'height': 172,
      'bed': 1,
      'emergencyContact': {
        'firstName': 'Will',
        'lastName': 'Fung',
        'relationship': 'Father',
        'phone': 59046983,
      },
      'preexistingConditions': ['high blood pressure', 'asthma', 'cancer'],
      'familyHistory': [
        {
          'firstName': 'Will',
          'lastName': 'Fung',
          'relationship': 'Father',
          'conditions': ['high blood pressure'],
        },
        {
          'firstName': 'Lynn',
          'lastName': 'Fung',
          'relationship': 'Mother',
          'conditions': ['anemia'],
        },
      ],
      'normal': true,
    },
    {
      'patientId': 124,
      'firstName': 'AJ',
      'lastName': 'Grande',
      'DOB': 10301882,
      'Image': require('./assets/elderlymanavatar2.png'),
      'Age': 134,
      'roomNum': 102,
      'weight': 100,
      'height': 30,
      'bed': 2,
      'emergencyContact': {
        'firstName': 'Albert',
        'lastName': 'Grande',
        'relationship': 'Brother',
        'phone': 5540507403,
      },
      'preexistingConditions': ['erectile disfunction', 'bipolar'],
      'familyHistory': [
        {
          'firstName': 'Bob',
          'lastName': 'Li',
          'relationship': 'Father',
          'conditions': ['kidney cancer'],
        },
        {
          'firstName': 'Bronwyn',
          'lastName': 'Li',
          'relationship': 'Mother',
          'conditions': ['black lung'],
        },
      ],
      'normal': true,
    },
    {
      'patientId': 125,
      'firstName': 'Kent',
      'lastName': 'Lee',
      'DOB': 6202015,
      'Image': require('./assets/elderlymanavatar3.png'),
      'Age': 28,
      'roomNum': 103,
      'weight': 149,
      'height': 173,
      'bed': 3,
      'emergencyContact': {
        'firstName': 'Will',
        'lastName': 'Li',
        'relationship': 'Father',
        'phone': 59046983,
      },
      'preexistingConditions': ['high blood pressure', 'asthma', 'cancer'],
      'familyHistory': [
        {
          'firstName': 'Will',
          'lastName': 'Fung',
          'relationship': 'Father',
          'conditions': ['high blood pressure'],
        },
        {
          'firstName': 'Lynn',
          'lastName': 'Fung',
          'relationship': 'Mother',
          'conditions': ['anemia'],
        },
      ],
      'normal': true,
    },
    {
      'patientId': 126,
      'firstName': 'Nam',
      'lastName': 'Dao',
      'DOB': 6202015,
      'Image': require('./assets/elderlymanavatar4.png'),
      'Age': 1000,
      'roomNum': 104,
      'weight': 55,
      'height': 160,
      'bed': 4,
      'emergencyContact': {
        'firstName': 'Jake',
        'lastName': 'Trinh',
        'relationship': 'Father',
        'phone': 59046983,
      },
      'preexistingConditions': ['high blood pressure', 'asthma', 'cancer'],
      'familyHistory': [
        {
          'firstName': 'Jake',
          'lastName': 'Trinh',
          'relationship': 'Father',
          'conditions': ['high blood pressure'],
        },
        {
          'firstName': 'Lynn',
          'lastName': 'Dao',
          'relationship': 'Mother',
          'conditions': ['anemia'],
        },
      ],
      'normal': true,
    },
    {
      'patientId': 127,
      'firstName': 'Kristine',
      'lastName': 'Yuen',
      'DOB': 4211582,
      'Image': require('./assets/elderlywomanavatar5.png'),
      'Age': 10,
      'roomNum': 105,
      'weight': 50,
      'height': 150,
      'bed': 5,
      'emergencyContact': {
        'firstName': 'Mark',
        'lastName': 'Yuen',
        'relationship': 'Father',
        'phone': 59046983,
      },
      'preexistingConditions': ['high blood pressure', 'asthma', 'cancer'],
      'familyHistory': [
        {
          'firstName': 'Mark',
          'lastName': 'Yuen',
          'relationship': 'Father',
          'conditions': ['high blood pressure'],
        },
        {
          'firstName': 'Lynn',
          'lastName': 'Yuen',
          'relationship': 'Mother',
          'conditions': ['anemia'],
        },
      ],
      'normal': true,
    },
    {
      'patientId': 128,
      'firstName': 'John',
      'lastName': 'Doe',
      'DOB': 4211540,
      'Image': 'http://www.soulsoupsf.org/wp-content/uploads/2015/09/elderly-man.jpg',
      'Age': 100,
      'roomNum': 106,
      'weight': 50,
      'height': 150,
      'bed': 6,
      'emergencyContact': {
        'firstName': 'Mark',
        'lastName': 'Doe',
        'relationship': 'Father',
        'phone': 59046983,
      },
      'preexistingConditions': ['high blood pressure', 'asthma', 'cancer'],
      'familyHistory': [
        {
          'firstName': 'Mark',
          'lastName': 'Doe',
          'relationship': 'Father',
          'conditions': ['high blood pressure'],
        },
        {
          'firstName': 'Lynn',
          'lastName': 'Doe',
          'relationship': 'Mother',
          'conditions': ['anemia'],
        },
      ],
      'normal': true,
    },
  ],
};

export default data;
